# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

R_hunspell_check <- function(affix, dict, words, ignore) {
    .Call('hunspell_R_hunspell_check', PACKAGE = 'hunspell', affix, dict, words, ignore)
}

R_hunspell_suggest <- function(affix, dict, words) {
    .Call('hunspell_R_hunspell_suggest', PACKAGE = 'hunspell', affix, dict, words)
}

R_hunspell_analyze <- function(affix, dict, words) {
    .Call('hunspell_R_hunspell_analyze', PACKAGE = 'hunspell', affix, dict, words)
}

R_hunspell_stem <- function(affix, dict, words) {
    .Call('hunspell_R_hunspell_stem', PACKAGE = 'hunspell', affix, dict, words)
}

R_hunspell_find <- function(affix, dict, text, ignore, format) {
    .Call('hunspell_R_hunspell_find', PACKAGE = 'hunspell', affix, dict, text, ignore, format)
}

